receivers:
  otlp:
    protocols:
      http: {}
      grpc: {}

exporters:
  logging:
    verbosity: detailed
  otlphttp/jaeger:
    endpoint: "http://jaeger:4318"
    tls:
      insecure: true

processors:
  batch: {}

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlphttp/jaeger]
