overrides:
  metrics_generator_processors: []
server:
  http_listen_port: 3200
  grpc_listen_port: 4318
storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks
