"""Executor synthesising dry-run artefacts for a plan."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any


def _render_pr_diff(plan: dict[str, Any]) -> str:
    plan_id = plan.get("id", "unknown")
    title = plan.get("title", "Investigate incident")
    steps = plan.get("steps", [])
    if not isinstance(steps, list):
        steps = list(steps) if hasattr(steps, "__iter__") else []
    body_lines = "\n".join(f"+ # {step}" for step in steps)
    return (
        "diff --git a/tests/integration/test_artifacts.py b/tests/integration/test_artifacts.py\n"
        "--- a/tests/integration/test_artifacts.py\n"
        "+++ b/tests/integration/test_artifacts.py\n"
        "@@\n"
        f"+# Plan: {title} ({plan_id})\n"
        f"{body_lines}\n"
        "+# NOTE: Generated by OverhearOps demo\n"
    )


def _render_jira(plan: dict[str, Any]) -> dict[str, Any]:
    now = datetime.now(UTC).isoformat()
    steps = plan.get("steps", [])
    if not isinstance(steps, list):
        steps = list(steps) if hasattr(steps, "__iter__") else []
    return {
        "summary": f"[Dry Run] {plan.get('title', 'Investigate incident')}",
        "description": "\n".join(
            [
                f"Hypothesis: {plan.get('hypothesis', 'Triage incident')}",
                f"Blast radius: {plan.get('blast_radius', 'Unknown')}",
                "Steps:",
                *[f"- {step}" for step in steps],
            ]
        ),
        "labels": ["overhearops", plan.get("id", "plan-unknown")],
        "generated_at": now,
    }


def try_patch_or_issue(plan: dict[str, Any]) -> dict[str, Any]:
    """Produce artefacts for the chosen plan (stubbed for demo)."""

    if not plan:
        return {
            "plan": {},
            "pr_diff": "",
            "jira": {},
            "notes": ["No plan selected"],
        }
    notes = [
        "Team coverage: coordinator, fixer, critic, riskguard",
        f"Confidence estimate: {plan.get('confidence', 0.0):.2f}",
    ]
    return {
        "plan": plan,
        "pr_diff": _render_pr_diff(plan),
        "jira": _render_jira(plan),
        "notes": notes,
    }


__all__ = ["try_patch_or_issue"]
